[package]
name = "azcli"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
lazy_static = "1.4.0"
regex = "1.5"
colored = "3.0.0"
color-eyre = "0.6.5"
clap = { version = "4.5.39", features = ["derive"] }
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
